name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            components/audio/pwm_audio;
            components/bluetooth/ble_conn_mgr;
            components/bluetooth/ble_profiles/esp/ble_ota;
            components/bootloader_support_plus;
            components/button;
            components/display/lcd/esp_lcd_panel_io_additions;
            components/extended_vfs;
            components/gprof;
            components/knob;
            components/led/led_indicator;
            components/led/lightbulb_driver;
            components/openai;
            components/usb/esp_tinyuf2;
            components/usb/iot_usbh;
            components/usb/iot_usbh_cdc;
            components/usb/iot_usbh_modem;
            components/usb/usb_stream;
            components/utilities/xz;
            tools/cmake_utilities;
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
