.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps
    - python tools/build_apps.py ${EXAMPLE_DIR} -t all -vv

build_example_audio_wav_player:
  extends:
    - .build_examples_template
    - .rules:build:example_audio_wav_player
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/audio/wav_player

build_example_bluetooth_ble_conn_mgr_ble_periodic_adv:
  extends:
    - .build_examples_template
    - .rules:build:example_bluetooth_ble_conn_mgr
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/bluetooth/ble_conn_mgr/ble_periodic_adv

build_example_bluetooth_ble_conn_mgr_ble_periodic_sync:
  extends:
    - .build_examples_template
    - .rules:build:example_bluetooth_ble_conn_mgr
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/bluetooth/ble_conn_mgr/ble_periodic_sync

build_example_bluetooth_ble_conn_mgr_ble_spp_client:
  extends:
    - .build_examples_template
    - .rules:build:example_bluetooth_ble_conn_mgr
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.3
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/bluetooth/ble_conn_mgr/ble_spp/spp_client

build_example_bluetooth_ble_conn_mgr_ble_spp_server:
  extends:
    - .build_examples_template
    - .rules:build:example_bluetooth_ble_conn_mgr
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.3
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/bluetooth/ble_conn_mgr/ble_spp/spp_server

build_example_bluetooth_ble_ota:
  extends:
    - .build_examples_template
    - .rules:build:example_bluetooth_ble_ota
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/bluetooth/ble_ota

build_example_camera_basic:
  extends:
    - .build_examples_template
    - .rules:build:example_camera_basic
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/camera/basic

build_example_camera_pic_server:
  extends:
    - .build_examples_template
    - .rules:build:example_camera_pic_server
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/camera/pic_server

build_example_camera_test_framerate:
  extends:
    - .build_examples_template
    - .rules:build:example_camera_test_framerate
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/camera/test_framerate

build_example_camera_video_recorder:
  extends:
    - .build_examples_template
    - .rules:build:example_camera_video_recorder
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/camera/video_recorder

build_example_camera_video_stream_server:
  extends:
    - .build_examples_template
    - .rules:build:example_camera_video_stream_server
  variables:
    EXAMPLE_DIR: examples/camera/video_stream_server
    IMAGE: espressif/idf:release-v4.4

build_example_check_pedestrian_flow:
  extends:
    - .build_examples_template
    - .rules:build:example_check_pedestrian_flow
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
  variables:
    EXAMPLE_DIR: examples/check_pedestrian_flow

build_example_extended_vfs_gpio_gpio_simple:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_gpio_gpio_simple
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/gpio/gpio_simple

build_example_extended_vfs_i2c_i2c_bh1750:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_i2c_i2c_bh1750
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/i2c/i2c_bh1750

build_example_extended_vfs_i2c_i2c_tt21100:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_i2c_i2c_tt21100
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/i2c/i2c_tt21100

build_example_extended_vfs_ledc_ledc_simple:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_ledc_ledc_simple
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/ledc/ledc_simple

build_example_extended_vfs_spi_spi_master_simple:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_spi_spi_master_simple
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/spi/spi_master_simple

build_example_extended_vfs_spi_spi_slave_simple:
  extends:
    - .build_examples_template
    - .rules:build:example_extended_vfs_spi_spi_slave_simple
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/extended_vfs/spi/spi_slave_simple

build_example_get_started_blink:
  extends:
    - .build_examples_template
    - .rules:build:example_get_started_blink
  variables:
    EXAMPLE_DIR: examples/get-started/blink
    IMAGE: espressif/idf:release-v4.4

build_example_gprof_gprof_simple:
  extends:
    - .build_examples_template
    - .rules:build:example_gprof_gprof_simple
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/gprof/gprof_simple

build_example_hmi_lvgl_coffee:
  extends:
    - .build_examples_template
    - .rules:build:example_hmi_lvgl_coffee
  variables:
    EXAMPLE_DIR: examples/hmi/lvgl_coffee
    IMAGE: espressif/idf:release-v4.4

build_example_hmi_lvgl_example:
  extends:
    - .build_examples_template
    - .rules:build:example_hmi_lvgl_example
  variables:
    EXAMPLE_DIR: examples/hmi/lvgl_example
    IMAGE: espressif/idf:release-v4.4

build_example_hmi_lvgl_thermostat:
  extends:
    - .build_examples_template
    - .rules:build:example_hmi_lvgl_thermostat
  variables:
    EXAMPLE_DIR: examples/hmi/lvgl_thermostat
    IMAGE: espressif/idf:release-v4.4

build_example_hmi_lvgl_wificonfig:
  extends:
    - .build_examples_template
    - .rules:build:example_hmi_lvgl_wificonfig
  variables:
    EXAMPLE_DIR: examples/hmi/lvgl_wificonfig
    IMAGE: espressif/idf:release-v4.4

build_example_lighting_lightbulb:
  extends:
    - .build_examples_template
    - .rules:build:example_lighting_lightbulb
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/lighting/lightbulb

build_example_ota_simple_ota_example:
  extends:
    - .build_examples_template
    - .rules:build:example_ota_simple_ota_example
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/ota/simple_ota_example
    WARNING_STR: "1/2 app partitions are too small"

build_example_screen:
  extends:
    - .build_examples_template
    - .rules:build:example_screen
  variables:
    EXAMPLE_DIR: examples/screen
    IMAGE: espressif/idf:release-v4.4

build_example_sensors_sensor_control_led:
  extends:
    - .build_examples_template
    - .rules:build:example_sensors_sensor_control_led
  variables:
    EXAMPLE_DIR: examples/sensors/sensor_control_led
    IMAGE: espressif/idf:release-v4.4

build_example_sensors_sensor_hub_monitor:
  extends:
    - .build_examples_template
    - .rules:build:example_sensors_sensor_hub_monitor
  variables:
    EXAMPLE_DIR: examples/sensors/sensor_hub_monitor
    IMAGE: espressif/idf:release-v4.4

build_example_usb_device_usb_msc_wireless_disk:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_device_usb_msc_wireless_disk
  variables:
    EXAMPLE_DIR: examples/usb/device/usb_msc_wireless_disk
    IMAGE: espressif/idf:release-v5.0

build_example_usb_device_usb_surface_dial:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_device_usb_surface_dial
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/device/usb_surface_dial

build_example_usb_device_usb_uf2_nvs:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_device_usb_uf2_nvs
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/device/usb_uf2_nvs

build_example_usb_device_usb_uf2_ota:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_device_usb_uf2_ota
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/device/usb_uf2_ota

build_example_usb_host_usb_camera_lcd_display:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_host_usb_camera_lcd_display
  variables:
    EXAMPLE_DIR: examples/usb/host/usb_camera_lcd_display
    IMAGE: espressif/idf:release-v5.0

build_example_usb_host_usb_camera_mic_spk:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_host_usb_camera_mic_spk
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/host/usb_camera_mic_spk

build_example_usb_host_usb_audio_player:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_host_usb_audio_player
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/host/usb_audio_player

build_example_usb_host_usb_cdc_4g_module:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_host_usb_cdc_4g_module
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/usb/host/usb_cdc_4g_module

build_example_utilities_xz_decompress_file:
  extends:
    - .build_examples_template
    - .rules:build:example_utilities_xz_decompress_file
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: examples/utilities/xz_decompress_file

build_components_knob_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:components_knob_test
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: components/knob/test_apps

build_components_openai_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:components_openai_test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: components/openai/test_apps

build_components_usb_usb_stream_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:components_usb_usb_stream_test
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: components/usb/usb_stream/test_apps

build_components_display_lcd_esp_lcd_panel_io_additions_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:components_display_lcd_esp_lcd_panel_io_additions_test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: components/display/lcd/esp_lcd_panel_io_additions/test_apps

build_components_led_led_indicator_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:components_led_led_indicator_test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: components/led/led_indicator/test_apps

build_tools_cmake_utilities_test_apps:
  extends:
    - .build_examples_template
    - .rules:build:tools_cmake_utilities_test_apps
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v4.4
      - IMAGE: espressif/idf:release-v5.0
  variables:
    EXAMPLE_DIR: tools/cmake_utilities/test_apps
